pipeline:
  name: child_remote_with_manualIntervention
  identifier: child_remote_with_manualIntervention
  projectIdentifier: Test_AR7
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: exit 0
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
                  failureStrategies:
                    - onFailure:
                        errors:
                          - AllErrors
                        action:
                          type: ManualIntervention
                          spec:
                            timeout: 10m
                            onTimeout:
                              action:
                                type: MarkAsFailure
        tags: {}
