pipeline:
  name: custom
  identifier: custom
  projectIdentifier: CDCNGAuto_TriggerProjMn60TcuSgr
  orgIdentifier: CDCNGAuto_TriggerOrgAutovMPZUeDJI7
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Http
                  name: Http_1
                  identifier: Http_1
                  timeout: 10s
                  spec:
                    url: https://qa.harness.io/gateway/pipeline/api/webhook/custom/Y6wnT3qZSRSU7socEnv0MQ/v3?accountIdentifier=rXUXvbFqRr2XwcjBu3Oq-Q&orgIdentifier=CDCNGAuto_TriggerOrgAutovMPZUeDJI7&projectIdentifier=CDCNGAuto_TriggerProjMn60TcuSgr&pipelineIdentifier=pl_auto_pipeline_TwqvU&triggerIdentifier=CDCNGAuto_Custom_Webhook_Trigger_KYVu6sfkTs
                    method: GET
                    headers: []
                    inputVariables: []
                    outputVariables: []
                    requestBody: "{\"sample_key\": \"sample_value\"}"
        tags: {}
