pipeline:
  name: fall back check1
  identifier: fall_back_check1
  projectIdentifier: AmitTest
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: stage1
        identifier: stage1
        template:
          templateRef: Stage1Caching
          versionLabel: "2"
          templateInputs:
            type: Deployment
            spec:
              infrastructure:
                infrastructureDefinition:
                  type: KubernetesDirect
                  spec:
                    connectorRef: <+input>
                    namespace: <+input>
