pipeline:
  name: 04FebPipeline-1
  identifier: FebPipeline1
  projectIdentifier: AmitTest
  orgIdentifier: Pipelines_NonK8s_Org_NG
  tags: {}
  stages:
    - stage:
        name: stage1
        identifier: stage1
        tags: {}
        template:
          templateRef: stage04Feb1
          versionLabel: v1
          templateInputs:
            type: Custom
            spec:
              execution:
                steps:
                  - step:
                      identifier: step12
                      template:
                        templateInputs:
                          type: ShellScript
                          spec:
                            source:
                              type: Inline
                              spec:
                                script: <+input>
                            environmentVariables:
                              - name: var1
                                type: String
                                value: <+input>
    - stage:
        name: stage2
        identifier: stage2
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  name: step23
                  identifier: step23
                  template:
                    templateRef: StepTemplate04Feb
                    versionLabel: v1
                    templateInputs:
                      type: ShellScript
                      spec:
                        source:
                          type: Inline
                          spec:
                            script: <+input>
                        environmentVariables:
                          - name: var1
                            type: String
                            value: <+input>
        tags: {}
