pipeline:
  name: inlineTempRef
  identifier: inlineTempRef
  projectIdentifier: AmitTest
  orgIdentifier: GitXOrg
  tags: {}
  stages:
    - stage:
        name: ste1
        identifier: ste1
        template:
          templateRef: Jan13Stage2
          versionLabel: "1"
          templateInputs:
            type: Custom
            spec:
              execution:
                steps:
                  - step:
                      identifier: step2
                      template:
                        templateInputs:
                          type: ShellScript
                          timeout: <+input>
                          spec:
                            source:
                              type: Inline
                              spec:
                                script: <+input>
