pipeline:
  name: parent pipe1 feb28
  identifier: parent_pipe1_feb28
  projectIdentifier: TestAmit
  orgIdentifier: Simlified_Git_sync
  tags: {}
  stages:
    - stage:
        name: S23
        identifier: S2
        description: ""
        type: Pipeline
        spec:
          org: Simlified_Git_sync
          pipeline: childPipeline1_feb27
          project: TestAmit
          inputs:
            identifier: childPipeline1_feb27
            stages:
              - stage:
                  identifier: S1
                  type: Custom
                  spec:
                    execution:
                      steps:
                        - step:
                            identifier: ShellScript_1
                            type: ShellScript
                            spec:
                              source:
                                type: Inline
                                spec:
                                  script: <+input>
        tags: {}
