pipeline:
  name: Pipe3Dec12
  identifier: Pipe3Dec12
  projectIdentifier: AmitTest
  orgIdentifier: GitXOrg
  tags: {}
  stages:
    - stage:
        name: Asdw3
        identifier: Asdw3
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: As2
                  identifier: As2
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    approverInputs: []
        tags: {}
    - stage:
        name: Asdw1
        identifier: Asdw1
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: As2
                  identifier: As2
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    approverInputs: []
        tags: {}
  description: abc
