pipeline:
  name: pipeline29June
  identifier: pipeline29June
  template:
    templateRef: pipeline29June
    versionLabel: "1"
    templateInputs:
      stages:
        - stage:
            identifier: stage1
            template:
              templateInputs:
                type: Custom
                spec:
                  execution:
                    steps:
                      - step:
                          identifier: step1
                          template:
                            templateInputs:
                              type: ShellScript
                              timeout: <+input>
                              spec:
                                source:
                                  type: Inline
                                  spec:
                                    script: <+input>
  tags: {}
  projectIdentifier: AmitTest
  orgIdentifier: GitXOrg
