pipeline:
  name: pipe2Dec13
  identifier: pipe2Dec13
  projectIdentifier: AmitTest
  orgIdentifier: GitXOrg
  tags: {}
  stages:
    - stage:
        name: stage1
        identifier: stage1
        template:
          templateRef: stageDec13
          versionLabel: v1
    - stage:
        name: stage2
        identifier: stage2
        template:
          templateRef: k8sMigration12Dec
          versionLabel: "1"
          templateInputs:
            type: Deployment
            spec:
              serviceConfig:
                serviceDefinition:
                  type: Kubernetes
                  spec:
                    manifests:
                      - manifest:
                          identifier: manifest1
                          type: Kustomize
                          spec:
                            store:
                              type: Github
                              spec:
                                repoName: <+input>
              infrastructure:
                infrastructureDefinition:
                  type: KubernetesDirect
                  spec:
                    connectorRef: <+input>
                    namespace: abc
    - stage:
        name: stage3
        identifier: stage3
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Wait
                  name: grd
                  identifier: grd
                  spec:
                    duration: 10m
        tags: {}
