pipeline:
  name: remote_input_pipe38r302
  identifier: remote_input_pipe38r302
  projectIdentifier: DoNotDelete_AR7
  orgIdentifier: Ng_Pipelines_K8s_Organisations
  tags: {}
  stages:
    - stage:
        name: s
        identifier: s
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: exit 0
                    environmentVariables: []
                    outputVariables: []
                  timeout: <+input>
        tags: {}
