pipeline:
  name: TestParent
  identifier: TestParent
  projectIdentifier: TestAmit
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: S1
        identifier: S1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Wait
                  name: Wait_1
                  identifier: Wait_1
                  spec:
                    duration: 10s
        tags: {}
    - stage:
        name: S12
        identifier: S12
        description: ""
        type: Pipeline
        spec:
          org: default
          pipeline: TestChild
          project: TestAmit
