pipeline:
  name: testPipeline04Feb
  identifier: testPipeline04Feb
  tags: {}
  template:
    templateRef: pipelineTemplate
    versionLabel: v1
    templateInputs:
      stages:
        - stage:
            identifier: s1
            template:
              templateInputs:
                type: Custom
                spec:
                  execution:
                    steps:
                      - step:
                          identifier: ShellScript_1
                          type: ShellScript
                          spec:
                            source:
                              type: Inline
                              spec:
                                script: <+input>
  projectIdentifier: AmitTest
  orgIdentifier: Pipelines_NonK8s_Org_NG
