pipeline:
  name: test gitwebhook sync
  identifier: test_gitwebhook_sync
  projectIdentifier: AmitTest
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: S12
        identifier: S12
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo 'hello123'
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
