pipeline:
  name: Trigger Test Remote
  identifier: Trigger_Test_Remote
  projectIdentifier: main_cypress_project_Krzysztof_Neumann
  orgIdentifier: default2
  tags: {}
  stages:
    - stage:
        name: S1
        identifier: S1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo Step S1
                    environmentVariables: []
                    outputVariables: []
                  timeout: <+input>
        tags: {}
    - stage:
        name: S2
        identifier: S2
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  name: Shell Script Template
                  identifier: Shell_Script_Template
                  template:
                    templateRef: Shell_Script_Template
                    versionLabel: V1
                    templateInputs:
                      type: ShellScript
                      timeout: <+input>
        tags: {}
